### ISSUE TITLE
Assignment 2: Part 2 - Architecture Diagram

### ISSUE THREAD

**Issue by RWenger** [RWenger/Code-Search-Engine-CS3704#2]
Pick one (or multiple) architectural style(s) that best fit(s) your project. Draw an architecture diagram for your project that follows your selected style(s). In your diagram, the component names should be specific to your project (instead of their names in the architectural style). Write a brief text explaining how the components of your architecture diagram correspond to those defined in the architectural style that they follow.

It is ok to mix multiple architectural styles for your project. Make sure to mention which architectural style(s) you chose. If you are mixing multiple architectural styles, make sure you mention which parts of your architecture follow which styles.

The terminology used in this diagram should also be consistent with the one used in your requirements analysis.

**Comment by MegaArman** [comment]
I can do an MVC diagram this weekend probably

**Comment by MegaArman** [comment]
Uploaded to the Assignment 2 folder
